name: face_detector_mlkit
description: "Detector Face - DF MLKIT - App desenvolvido em flutter para reconhecimentos de faces"

version: 6.0.0+1

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_face_mesh_detection: ^0.4.1
  image_picker: ^1.1.2
  camera: ^0.11.1
  camera_android: ^0.10.10+1
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_pdfview: ^1.4.0
  google_mlkit_commons: ^0.11.0
  url_launcher: ^6.3.1
  store_redirect: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

